import React, { useEffect, useState } from 'react';
import { Config } from '../types';
import { X, Printer, MessageCircle, Mail, Copy, Check, FileDown, Share2 } from 'lucide-react';
import { generateReportPDF, shareOrDownloadPDF } from '../utils/pdfExport';

interface PrintReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: Config;
  reportTitle: string;
  fromDate: string;
  toDate: string;
  headers: string[];
  rows: any[][];
  totals?: any[];
  summaryCards?: { label: string; value: string | number; color?: string }[];
}

export const PrintReportModal: React.FC<PrintReportModalProps> = ({
  isOpen,
  onClose,
  config,
  reportTitle,
  fromDate,
  toDate,
  headers,
  rows,
  totals,
  summaryCards
}) => {
  const [copied, setCopied] = useState(false);
  const [phoneInput, setPhoneInput] = useState('');
  const [showPhonePrompt, setShowPhonePrompt] = useState(false);

  const nowStr = new Date().toLocaleString();

  const generateReportSummaryText = () => {
    const lines = [
      `📊 *${reportTitle.toUpperCase()}*`,
      `🏢 *${config.CompanyName || 'Store'}*`,
      `📅 Period: ${fromDate} to ${toDate}`,
      `⏰ Generated: ${nowStr}`,
      '--------------------------------',
      ...(summaryCards && summaryCards.length > 0
        ? [
            '*KEY METRICS:*',
            ...summaryCards.map(c => `• ${c.label}: *${c.value}*`),
            '--------------------------------'
          ]
        : []),
      `*TOTAL RECORDS:* ${rows.length}`,
      ...(totals && totals.length > 0
        ? [
            '*TOTALS SUMMARY:*',
            ...totals
              .map((t, i) => (t !== undefined && t !== null && String(t).trim() !== '' ? `• ${headers[i] || 'Total'}: *${t}*` : ''))
              .filter(Boolean),
            '--------------------------------'
          ]
        : []),
      `Generated by ${config.CompanyName || 'Smart POS System'}`
    ];
    return lines.join('\n');
  };

  const handleWhatsAppShare = () => {
    const cleanPhone = phoneInput.replace(/[^0-9]/g, '');
    const message = encodeURIComponent(generateReportSummaryText());
    let url = `https://wa.me/?text=${message}`;
    if (cleanPhone && cleanPhone.length >= 7) {
      url = `https://wa.me/${cleanPhone}?text=${message}`;
    }
    window.open(url, '_blank', 'noopener,noreferrer');
    setShowPhonePrompt(false);
  };

  const handleEmailShare = () => {
    const subject = encodeURIComponent(`${reportTitle} (${fromDate} - ${toDate}) - ${config.CompanyName || 'Store'}`);
    const body = encodeURIComponent(generateReportSummaryText());
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const handleCopyText = () => {
    navigator.clipboard.writeText(generateReportSummaryText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownloadPDF = () => {
    const doc = generateReportPDF(reportTitle, config, fromDate, toDate, headers, rows, totals, summaryCards);
    const safeTitle = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
    doc.save(`${safeTitle}_${fromDate}_to_${toDate}.pdf`);
  };

  const handleSharePDF = async () => {
    const doc = generateReportPDF(reportTitle, config, fromDate, toDate, headers, rows, totals, summaryCards);
    const safeTitle = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
    const filename = `${safeTitle}_${fromDate}_to_${toDate}.pdf`;
    await shareOrDownloadPDF(doc, filename, `${reportTitle} - ${config.CompanyName || 'Store'}`, generateReportSummaryText());
  };

  const generatePrintHTML = () => {
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${reportTitle} - ${config.CompanyName || 'Store'}</title>
        <style>
          @page {
            size: A4 portrait;
            margin: 10mm;
          }
          * {
            box-sizing: border-box;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            font-size: 11px;
            color: #0f172a;
            background: #fff;
            margin: 0;
            padding: 0;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          .header-container {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 2px solid #0f172a;
            padding-bottom: 12px;
            margin-bottom: 16px;
          }
          .company-name {
            font-size: 20px;
            font-weight: 800;
            color: #0f172a;
            letter-spacing: -0.5px;
            margin-bottom: 2px;
          }
          .company-meta {
            font-size: 10px;
            color: #475569;
            line-height: 1.4;
          }
          .report-badge {
            text-align: right;
          }
          .report-title {
            font-size: 16px;
            font-weight: 800;
            color: #1e1b4b;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .period-pill {
            display: inline-block;
            background: #e0e7ff;
            color: #3730a3;
            font-weight: 700;
            font-size: 10px;
            padding: 3px 8px;
            border-radius: 999px;
            margin-top: 4px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
            page-break-inside: auto;
          }
          tr {
            page-break-inside: avoid;
            page-break-after: auto;
          }
          thead {
            display: table-header-group;
          }
          tfoot {
            display: table-footer-group;
          }
          th {
            background-color: #f1f5f9;
            color: #1e293b;
            font-weight: 800;
            text-transform: uppercase;
            font-size: 9.5px;
            letter-spacing: 0.5px;
            padding: 8px 10px;
            border: 1px solid #cbd5e1;
            text-align: left;
          }
          td {
            padding: 7px 10px;
            border: 1px solid #e2e8f0;
            font-size: 10.5px;
          }
          tr:nth-child(even) td {
            background-color: #f8fafc;
          }
          .num {
            text-align: right;
            font-family: 'Courier New', Courier, monospace;
            font-weight: 600;
          }
          .center {
            text-align: center;
          }
          tfoot tr td {
            background-color: #f1f5f9;
            font-weight: 800;
            border-top: 2px solid #0f172a;
            border-bottom: 2px solid #0f172a;
            font-size: 11px;
          }
          .footer-section {
            margin-top: 40px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
            font-size: 10px;
            color: #64748b;
            border-top: 1px solid #e2e8f0;
            padding-top: 12px;
            page-break-inside: avoid;
          }
          .sig-line {
            width: 160px;
            border-top: 1px solid #94a3b8;
            text-align: center;
            padding-top: 4px;
            font-weight: 600;
            color: #334155;
          }
        </style>
      </head>
      <body>
        <div class="header-container">
          <div>
            <div class="company-name">${config.CompanyName || 'Business Store'}</div>
            <div class="company-meta">
              ${config.CompanyAddress ? `<span>${config.CompanyAddress}</span><br>` : ''}
              ${config.CompanyPhone ? `<span>Contact: ${config.CompanyPhone}</span>` : ''}
              ${config.GSTIN ? `<span> | GSTIN: ${config.GSTIN}</span>` : ''}
            </div>
          </div>
          <div class="report-badge">
            <div class="report-title">${reportTitle}</div>
            <div class="period-pill">Period: ${fromDate} to ${toDate}</div>
            <div style="font-size: 9px; color: #94a3b8; margin-top: 4px;">Printed: ${nowStr}</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              ${headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${rows.map(row => `
              <tr>
                ${row.map((cell: any) => {
                  const isNum = typeof cell === 'number' || (!isNaN(Number(cell)) && String(cell).includes('.') && !isNaN(parseFloat(cell)));
                  return `<td class="${isNum ? 'num' : ''}">${cell ?? '-'}</td>`;
                }).join('')}
              </tr>
            `).join('')}
          </tbody>
          ${totals && totals.length > 0 ? `
            <tfoot>
              <tr>
                ${totals.map((t: any) => {
                  const isNum = typeof t === 'number' || (!isNaN(Number(t)) && String(t).includes('.') && !isNaN(parseFloat(t)));
                  return `<td class="${isNum ? 'num' : ''}">${t ?? ''}</td>`;
                }).join('')}
              </tr>
            </tfoot>
          ` : ''}
        </table>

        <div class="footer-section">
          <div>Computer Generated Report | ${config.CompanyName || 'Store'}</div>
          <div class="sig-line">Authorized Signatory</div>
        </div>
      </body>
      </html>
    `;
  };

  const handleExecutePrint = () => {
    const htmlContent = generatePrintHTML();
    const oldFrame = document.getElementById('report-print-iframe');
    if (oldFrame) {
      try { oldFrame.remove(); } catch {}
    }

    const iframe = document.createElement('iframe');
    iframe.id = 'report-print-iframe';
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);

    const doc = iframe.contentWindow?.document || iframe.contentDocument;
    if (doc) {
      doc.open();
      doc.write(htmlContent);
      doc.close();
      setTimeout(() => {
        try {
          iframe.contentWindow?.focus();
          iframe.contentWindow?.print();
        } catch (err) {
          console.error('Print iframe execution fallback:', err);
          window.print();
        }
      }, 250);
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;

      if (e.key === 'Escape') {
        e.preventDefault();
        e.stopPropagation();
        onClose();
        return;
      }

      if ((e.ctrlKey || e.metaKey) && (e.key === 'p' || e.key === 'P')) {
        e.preventDefault();
        e.stopPropagation();
        handleExecutePrint();
        return;
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose, handleExecutePrint]);

  if (!isOpen) return null;

  return (
    <div className="print-modal-overlay fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4">
      <div className="print-modal-container w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col rounded-2xl bg-white shadow-2xl border border-slate-200">
        {/* Top Control Bar (Hidden during print) */}
        <div className="no-print print-controls flex flex-wrap items-center justify-between px-5 py-3.5 border-b border-slate-200 bg-slate-50 shrink-0 gap-3">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-indigo-100 text-indigo-700 rounded-xl">
              <Printer className="h-5 w-5" />
            </div>
            <div>
              <h3 className="font-extrabold text-slate-900 text-sm sm:text-base">{reportTitle} - Print & Share</h3>
              <p className="text-xs text-slate-500 font-medium">Period: {fromDate} to {toDate} &bull; {rows.length} entries</p>
            </div>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            {/* Share PDF (Native Sheet / WhatsApp / Mail Attachment) */}
            <button
              type="button"
              onClick={handleSharePDF}
              className="inline-flex items-center gap-1.5 bg-violet-600 text-white hover:bg-violet-700 px-3 py-2 rounded-xl text-xs font-bold shadow-xs transition"
              title="Share attached PDF file via WhatsApp, Gmail, or device share"
            >
              <Share2 className="h-4 w-4" />
              <span>Share PDF</span>
            </button>

            {/* Download PDF */}
            <button
              type="button"
              onClick={handleDownloadPDF}
              className="inline-flex items-center gap-1.5 bg-slate-800 text-white hover:bg-slate-900 px-3 py-2 rounded-xl text-xs font-bold shadow-xs transition"
              title="Download clean Report PDF"
            >
              <FileDown className="h-4 w-4" />
              <span>Save PDF</span>
            </button>

            {/* Copy Summary */}
            <button
              type="button"
              onClick={handleCopyText}
              className="inline-flex items-center gap-1.5 bg-white border border-slate-300 text-slate-700 hover:bg-slate-100 px-3 py-2 rounded-xl text-xs font-bold shadow-xs transition"
              title="Copy summary text"
            >
              {copied ? <Check className="h-4 w-4 text-emerald-600" /> : <Copy className="h-4 w-4" />}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>

            {/* Print Clean Document */}
            <button
              type="button"
              onClick={handleExecutePrint}
              className="inline-flex items-center gap-1.5 bg-indigo-600 text-white hover:bg-indigo-700 px-3.5 py-2 rounded-xl text-xs font-bold shadow-sm transition"
              title="Print Clean Report Document (Ctrl+P)"
            >
              <Printer className="h-4 w-4" />
              <span>Print A4</span>
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-600 rounded-full hover:bg-slate-200 transition"
              title="Close (Esc)"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* WhatsApp Phone Prompt if toggled */}
        {showPhonePrompt && (
          <div className="px-5 py-2.5 bg-emerald-50 border-b border-emerald-200 flex items-center gap-2 text-xs">
            <MessageCircle className="h-4 w-4 text-emerald-600 shrink-0" />
            <input
              type="text"
              placeholder="Enter mobile number with country code (e.g. 97517123456) or leave blank for contacts..."
              value={phoneInput}
              onChange={e => setPhoneInput(e.target.value)}
              className="flex-1 px-3 py-1.5 rounded-lg border border-emerald-300 bg-white font-semibold text-slate-900 outline-none focus:ring-2 focus:ring-emerald-400"
              autoFocus
            />
            <button
              type="button"
              onClick={handleWhatsAppShare}
              className="px-3 py-1.5 bg-emerald-600 text-white font-bold rounded-lg hover:bg-emerald-700 transition"
            >
              Send
            </button>
            <button
              type="button"
              onClick={() => setShowPhonePrompt(false)}
              className="p-1 text-slate-400 hover:text-slate-600 rounded"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        )}

        {/* Printable Document View Canvas */}
        <div className="print-modal-body flex-1 overflow-y-auto p-8 bg-slate-100/70">
          <div className="print-report-sheet max-w-3xl mx-auto bg-white p-8 rounded-xl shadow-lg border border-slate-200 space-y-6 text-slate-900 text-xs">
            {/* Header */}
            <div className="flex justify-between items-start pb-4 border-b-2 border-slate-900">
              <div>
                <h1 className="text-xl font-black text-slate-900 tracking-tight">{config.CompanyName || 'Business Store'}</h1>
                <p className="text-slate-500 text-[11px] mt-0.5">
                  {config.CompanyAddress && <span>{config.CompanyAddress} | </span>}
                  {config.CompanyPhone && <span>Contact: {config.CompanyPhone}</span>}
                  {config.GSTIN && <span> | GSTIN: {config.GSTIN}</span>}
                </p>
              </div>
              <div className="text-right">
                <span className="text-sm font-extrabold text-indigo-950 uppercase">{reportTitle}</span>
                <div className="text-[10px] font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded-full inline-block mt-1">
                  Period: {fromDate} to {toDate}
                </div>
                <div className="text-[10px] text-slate-400 mt-1">Printed: {nowStr}</div>
              </div>
            </div>

            {/* Table */}
            <div className="overflow-x-auto border border-slate-200 rounded-xl">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-slate-100 text-slate-800 font-bold uppercase text-[10px] tracking-wider border-b border-slate-200">
                    {headers.map((h, i) => (
                      <th key={i} className="py-2.5 px-3 text-left border-r border-slate-200 last:border-r-0">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {rows.map((row, rIdx) => (
                    <tr key={rIdx} className="hover:bg-slate-50">
                      {row.map((cell: any, cIdx: number) => {
                        const isNum = typeof cell === 'number' || (!isNaN(Number(cell)) && String(cell).includes('.') && !isNaN(parseFloat(cell)));
                        return (
                          <td key={cIdx} className={`py-2 px-3 border-r border-slate-100 last:border-r-0 ${isNum ? 'text-right font-mono font-medium' : ''}`}>
                            {cell ?? '-'}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
                {totals && totals.length > 0 && (
                  <tfoot>
                    <tr className="bg-slate-100 font-extrabold border-t-2 border-slate-900 text-slate-900 text-xs">
                      {totals.map((t: any, i: number) => {
                        const isNum = typeof t === 'number' || (!isNaN(Number(t)) && String(t).includes('.') && !isNaN(parseFloat(t)));
                        return (
                          <td key={i} className={`py-2.5 px-3 border-r border-slate-200 last:border-r-0 ${isNum ? 'text-right font-mono' : ''}`}>
                            {t ?? ''}
                          </td>
                        );
                      })}
                    </tr>
                  </tfoot>
                )}
              </table>
            </div>

            {/* Signatures */}
            <div className="pt-8 flex justify-between items-end text-slate-500 text-[11px]">
              <div>Computer Generated Report | {config.CompanyName || 'Store'}</div>
              <div className="w-40 border-t border-slate-400 text-center pt-1 font-semibold text-slate-700">
                Authorized Signatory
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

